[package]
name = "sweetiebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-model = "0.13.0"
twilight-http = "0.13.0"
twilight-gateway = "0.13.0"
twilight-cache-inmemory = "0.13.0"
twilight-standby = "0.13.0"
twilight-util = "0.13.0"
twilight-mention = "0.13.0"