[package]
name = "sweetiebot"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-model = "0.13"
twilight-http = { version = "0.13", features = ["rustls-native-roots", "simd-json"] }
twilight-gateway = { version = "0.13", features = ["rustls-native-roots", "simd-json"] }
twilight-cache-inmemory = "0.13"
twilight-standby = "0.13"
twilight-util = { version = "0.13", features = ["builder"]}
twilight-mention = "0.13"
twilight-interactions = "0.13"
futures = "0.3"
tokio = { version = "1.20", features = ["full"] }
tokio-stream = "0.1.9"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1.9.0"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json", "gzip"] }
scraper = "0.13.0"
urlencoding = "2.1.0"